apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudpilot-config
  namespace: cloudpilot

data:
  POSTGRES_USER: "postgres"

  CORE_DATABASE_URL: "jdbc:postgresql://postgres:5432/cloudpilot_db"
  AUDIT_DATABASE_URL: "jdbc:postgresql://postgres:5432/cloudpilot_audit_db"

  REDIS_HOST: "redis"
  REDIS_PORT: "6379"

  REDIS_CONNECT_TIMEOUT: "1s"
  REDIS_COMMAND_TIMEOUT: "1s"

  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"

  AUDIT_SERVICE_BASE_URL: "http://audit-service:8082"
