apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
  namespace: cloudpilot

spec:
  type: ClusterIP

  selector:
    app: kafka-exporter

  ports:
    - name: metrics
      port: 9308
      targetPort: 9308

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  namespace: cloudpilot

spec:
  replicas: 1

  selector:
    matchLabels:
      app: kafka-exporter

  template:
    metadata:
      labels:
        app: kafka-exporter

    spec:
      containers:
        - name: kafka-exporter
          image: danielqsj/kafka-exporter:v1.9.0
          imagePullPolicy: IfNotPresent

          args:
            - "--kafka.server=kafka:9092"

          ports:
            - name: metrics
              containerPort: 9308

          startupProbe:
            tcpSocket:
              port: 9308
            periodSeconds: 3
            failureThreshold: 20

          readinessProbe:
            tcpSocket:
              port: 9308
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            tcpSocket:
              port: 9308
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3