apiVersion: v1
kind: Service
metadata:
  name: audit-service
  namespace: cloudpilot
spec:
  selector:
    app: audit-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-service
  namespace: cloudpilot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit-service
  template:
    metadata:
      labels:
        app: audit-service
    spec:
      serviceAccountName: cloudpilot-audit
      containers:
        - name: audit-service
          image: 296062568732.dkr.ecr.us-east-1.amazonaws.com/cloudpilot-dev-audit-service:69ab67a
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8082
          env:
            # --------------------------------------
            # OpenTelemetry
            # --------------------------------------
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/otel/opentelemetry-javaagent.jar"
            - name: OTEL_SERVICE_NAME
              value: "cloudpilot-audit"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_EXPORTER_OTLP_TRACES_PROTOCOL
              value: "http/protobuf"
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: "http://otel-collector:4318/v1/traces"
            - name: OTEL_TRACES_SAMPLER
              value: "always_on"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: OTEL_LOGS_EXPORTER
              value: "none"
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: cloudpilot-config
                  key: AUDIT_DATABASE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: cloudpilot-config
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudpilot-secrets
                  key: POSTGRES_PASSWORD
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: cloudpilot-config
                  key: KAFKA_BOOTSTRAP_SERVERS
          startupProbe:
            httpGet:
              path: /api/audit/health
              port: 8082
            periodSeconds: 5
            failureThreshold: 24
          readinessProbe:
            httpGet:
              path: /api/audit/health
              port: 8082
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/audit/health
              port: 8082
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
