apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudpilot
  namespace: cloudpilot
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:735058419920:certificate/579e6e95-9663-401c-9d2f-ce8083c8ad83
    alb.ingress.kubernetes.io/ssl-redirect: "443"
spec:
  ingressClassName: alb
  rules:
    - host: app.cloudpilot-vamshi.mywire.org
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: core-backend
                port:
                  number: 8081
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80