apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudpilot-core
  namespace: cloudpilot
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudpilot-audit
  namespace: cloudpilot
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudpilot-grafana
  namespace: cloudpilot